---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-1
  labels:
    type: local
spec:
  capacity:
#    storage: 20Gi
    storage: 1Gi    
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data2/lv-1
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-2
  labels:
    type: local
spec:
  capacity:
#    storage: 20Gi
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data2/lv-2
  persistentVolumeReclaimPolicy: Recycle
